<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SignIn</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>bf125fce-29a6-4151-9a60-cb6995f11bd0</testSuiteGuid>
   <testCaseLink>
      <guid>f878ecc6-656d-4fdc-943b-ef76aea1b355</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Signin/PA-TC-126 Tap on forgot password link</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>980aa16c-a316-4c4d-aa88-1b0871e6b1ab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Signin/PA-TC-127 Enter a unregistered email and press Change password button</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>781f0503-4a6b-4bd2-81fa-df8b88a47d35</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03a02e94-b0f5-458d-b525-8a93a507410f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cc15540b-22f4-4fd3-9690-f2f9fd341c82</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Signin/PA-TC-128 Enter a valid mail and press Change password button</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7af93c0-769d-4614-bcf2-cc6f3a8c8a04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8780b38-0574-43b8-8629-465cd2db5e5a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0b69362c-b068-4bd8-a9c4-b374a9850571</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Signin/PA-TC-129 Click on the link in the Change password email</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5de46488-3360-473f-8ee4-7834208a4cff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c6b1cbc7-dde5-4ddd-9a34-da37914d1dc9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Signin/PA-TC-130 Follow the instructions and reset password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>db625211-ae80-4afc-b4a1-57c0294a80d5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Signin/PA-TC-131 Enter correct username and password and signin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a439de3-b6b5-42d3-b269-fbeaf018d789</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42adba5d-df7d-4bea-8095-084ea2491588</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
